### ISSUE TITLE
/etc/default/ferm

### ISSUE THREAD

**Issue by le9i0nx** [debops/ansible-ferm#44]
Where to see where are these variables?
ansible_local.*
From the code and documentation I do not understand.
https://github.com/debops/ansible-ferm/blame/master/templates/etc/default/ferm.j2#L15-L18
You can show a simple example?

**Comment by drybjed** [comment]
They are created by the [root.yml](https://github.com/debops/debops-playbooks/blob/master/playbooks/root.yml) playbook, which deploys a [cap12s.fact](https://github.com/debops/debops-playbooks/blob/master/playbooks/files/etc/ansible/facts.d/cap12s.fact) script which generates list of active POSIX capabilities on a host.
