### ISSUE TITLE
Path ferm error

### ISSUE THREAD

**Issue by patrickheeney** [debops/ansible-ferm#52]
I just updated to the latest version and found this error:

```
TASK: [debops.ferm | Patch ferm init script] **********************************
failed: [default] => {"failed": true}
msg: src ./vendor/roles/debops.ferm/files/usr/local/src/ferm/init-hooks.patch doesn't exist or not readable
```

It appears related to https://github.com/ansible/ansible-modules-extras/issues/338

I have worked around it temporarily using `ferm_init_hooks: False`.

**Comment by drybjed** [comment]
This issue is fixed on current stable Ansible, but I've updated the role to make it work on older versions: https://github.com/debops/ansible-ferm/pull/53
