### ISSUE TITLE
daddr not working for accept rules

### ISSUE THREAD

**Issue by theMarix** [debops/ansible-ferm#99]
[The documentation](https://docs.debops.org/en/latest/ansible/roles/ansible-ferm/docs/rules.html#accept) describes the possibility to filter by destination address in accept rules. However, adding the parameter does not seem to affect the generated ferm rule and no effect can be observed. As far as I can see in `templates/etc/ferm/ferm.d/accept.conf.j2` the parameter is converted into an array, but not processed any further.

**Comment by gaudenz** [comment]
This is fixed with a94d831b0aa1456a3a1711d5dd5bc9d22609c9f4. Someone from debops needs to close this as I lack the permissions.
